// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/search.tsx";
import * as $$0 from "./islands/PlaceSearcher.tsx";
import * as $$1 from "./islands/PlaceSelector.tsx";
import * as $$2 from "./islands/Table.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/search.tsx": $2,
  },
  islands: {
    "./islands/PlaceSearcher.tsx": $$0,
    "./islands/PlaceSelector.tsx": $$1,
    "./islands/Table.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
